### ISSUE TITLE
在获取2022年12月之后的弹幕发生报错

### ISSUE THREAD

**Issue by andrew2010sun** [DNLINYJ/Biilibili_All_Danmu#2]
作者大佬你好！

我是使用的python3.11。我在获取2022年12月1日份起至之后的弹幕出现了下述报错。2022年12月以前的弹幕可正常获取。

我另外尝试了今年的视频，同样会报错。

希望您能帮忙解答，谢谢大佬！

Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\venv\Lib\site-packages\google\protobuf\internal\python_message.py", line 1128, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\venv\Lib\site-packages\google\protobuf\internal\python_message.py", line 1181, in InternalParse
    (data, new_pos) = decoder._DecodeUnknownField(
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\venv\Lib\site-packages\google\protobuf\internal\decoder.py", line 961, in _DecodeUnknownField
    (data, pos) = _DecodeUnknownFieldSet(buffer, pos) 
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\venv\Lib\site-packages\google\protobuf\internal\decoder.py", line 935, in _DecodeUnknownFieldSet
    (tag_bytes, pos) = ReadTag(buffer, pos)
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\venv\Lib\site-packages\google\protobuf\internal\decoder.py", line 174, in ReadTag
    while buffer[pos] & 0x80:
IndexError: index out of bounds on dimension 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\Main.py", line 193, in <module>
    Meum()
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\Main.py", line 123, in Meum
    result = GetAllDanmuInfo(user_input, headers)
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\GetAllDanmuInfo_V2.py", line 167, in GetAllDanmuInfo
    danmaku_seg.ParseFromString(req.content)
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\venv\Lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Users\xxx\Desktop\Biilibili_All_Danmu-master\venv\Lib\site-packages\google\protobuf\internal\python_message.py", line 1134, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by DNLINYJ** [comment]
大概率是B站在2022年12月之后修改了 Protobuf 数据包的格式，导致不能正常解析，我国庆的时候写下判断吧

**Comment by andrew2010sun** [comment]
谢谢大佬！！！ღ( ´･ᴗ･` )比心

**Comment by DNLINYJ** [comment]
更新了一下 proto 文件，你看下能用没有，以前的 proto 我跑完测试是没有问题的，可能是环境问题，但是还是跟随新版本比较好¯\_(ツ)_/¯

**Comment by DNLINYJ** [comment]
更新了一下 proto 文件，你看下能用没有，以前的 proto 我跑完测试是没有问题的，可能是环境问题，但是还是跟随新版本比较好¯\_(ツ)_/¯

**Comment by andrew2010sun** [comment]
好的大佬，这次是没问题了ღ( ´･ᴗ･` )
