### ISSUE TITLE
爬取2021年4月及更早视频出现 KeyError: 'data' 报错

### ISSUE THREAD

**Issue by zhengqiaozhi123** [DNLINYJ/Biilibili_All_Danmu#3]
使用Python 3.12，爬取2021年4月及更早的视频时都会出现下面的报错信息。我看大佬的测试用了2018年的视频，我也尝试了一下，同样会出现如下的错误。

希望您能帮忙解答，谢谢大佬！

Traceback (most recent call last):
  File "D:\Biilibili_All_Danmu-master\Main.py", line 193, in <module>
    Meum()
  File "D:\Biilibili_All_Danmu-master\Main.py", line 177, in Meum
    result = GetAllDanmuInfo(user_input, headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Biilibili_All_Danmu-master\GetAllDanmuInfo_V2.py", line 82, in GetAllDanmuInfo
    Time_list = RemoteBulitTimeList(
                ^^^^^^^^^^^^^^^^^^^^
  File "D:\Biilibili_All_Danmu-master\RemoteBulitTimeList.py", line 25, in RemoteBulitTimeList
    if json.loads(req.text)['data'] != None:
       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'data'

**Comment by DNLINYJ** [comment]
构建爬取时间列表那里报错了 我过几天看看吧

**Comment by ccicnce113424** [comment]
> 构建爬取时间列表那里报错了 我过几天看看吧

对cid1176840（av810872）实测，获取历史弹幕日期的api对于2021年6月以前的日期失效。建议使用弹幕自带的时间戳来判断下一个要获取的日期。

**Comment by DNLINYJ** [comment]
> > 构建爬取时间列表那里报错了 我过几天看看吧
> 
> 对cid1176840（av810872）实测，获取历史弹幕日期的api对于2021年6月以前的日期失效。建议使用弹幕自带的时间戳来判断下一个要获取的日期。

看了一下，貌似对2021年7月前的日期，api报 `-400` 错误，应该是在服务器端限制了，目前加了临时措施，出现这种情况直接走本地构建，已在 `36afe1d` 提交
